--- #YAML:1.0
name:                XLSperl
version:             0.6
abstract:            Use Perl "one-liners" with Microsoft Excel (.xls) files
license:             ~
author:              
    - Jon Allen <jj@jonallen.info>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Spreadsheet::ParseExcel:       0
    Spreadsheet::WriteExcel::Simple: 0
    Variable::Alias:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
