# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XLSperl
version:      0.03
version_from: bin/XLSperl
installdirs:  site
requires:
    Spreadsheet::ParseExcel:       0
    Spreadsheet::WriteExcel::Simple: 0
    Variable::Alias:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
